# Generated by Django 3.2.7 on 2021-09-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='numb',
            field=models.IntegerField(default=1337),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.CreateModel(
            name='MyOtherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherName', models.CharField(max_length=45)),
                ('numb', models.ForeignKey(default=1337, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.mymodel')),
            ],
        ),
    ]
